In [1]:
from sqlalchemy import create_engine
import pandas as pd
import xmlrpc.client


engine = create_engine(
    "postgresql+psycopg2://consulta:consulta@10.1.57.244:5432/dwfocco"
)
host = "10.1.57.244"
database = "dwfocco"
username = "consulta"
password = "consulta"

In [21]:
query = """
        SELECT rp.id, rp.nome_fan as nome_fan_representante, rp.cnpj, rp.descricao as nome_representante, rp.nome_fan 
        FROM trepresentantes as rp
        """

trep_focco = pd.read_sql(query, engine)

engine.dispose()

In [60]:
trep_focco

,id,nome_fan_representante,cnpj,nome_representante,nome_fan
0,561,L.S.A - PAULO,NaN,L.S.A - PAULO SERGIO PORTO,L.S.A - PAULO
1,645,ORI - ORIVALDO,1.437860e+13,ORIBORGES REPRESENTACOES COMERCIAL LTDA,ORI - ORIVALDO
2,647,SALLES & CAMARGO - DHIEGO,1.458547e+13,SALLES & CAMARGO - REPRESENTACOES COMERCIAIS L...,SALLES & CAMARGO - DHIEGO
3,761,MJ MIRANDA - THULHYO,2.619294e+13,MJ MIRANDA CARREIRO REPRESENTACOES LTDA,MJ MIRANDA - THULHYO
4,1001,LOREN K. FABRO PUPO,1.536387e+13,LOREN K. FABRO PUPO,LOREN K. FABRO PUPO
...,...,...,...,...,...
65,1281,UNICA 2,NaN,DANIELA DE BARROS AMORIM REPRESENTAÇÕES 2,UNICA 2
66,1301,LSA - PAULA FERNANDA SANTOS SOUSA,NaN,LSA - PAULA FERNANDA SANTOS SOUSA,LSA - PAULA FERNANDA SANTOS SOUSA
67,1441,LSA CORPORATIVO,NaN,LSA CORPORATIVO,LSA CORPORATIVO
68,1521,GRUPO SOHOME,NaN,GRUPO SOHOME,GRUPO SOHOME
69,648,GRX REPRESENTAÇÕES,1.716565e+13,GRX REPRESENTACOES COMERCIAIS LTDA,GRX REPRESENTAÇÕES

In [68]:
trep_focco.to_excel("representantes_focco2.xlsx", index=False)

In [71]:
trep_focco = pd.read_excel("representantes_focco.xlsx")

In [72]:
trep_focco.loc[trep_focco["ativo"]==True]

,Unnamed: 0,id,nome_fan_representante,cnpj,nome_representante,nome_fan,ativo
1,1,645,ORI - ORIVALDO,1.437860e+13,ORIBORGES REPRESENTACOES COMERCIAL LTDA,ORI - ORIVALDO,True
6,6,1221,ORI - JULIA,NaN,ORI - JULIA,ORI - JULIA,True
11,11,1461,A Z REPRESENTACOES LTDA,5.570747e+13,A Z REPRESENTACOES LTDA,A Z REPRESENTACOES LTDA,True
12,12,1481,LSA- LÍVIA MORELLI ANDRADE DOS SANTOS,NaN,LSA- LÍVIA MORELLI ANDRADE DOS SANTOS,LSA- LÍVIA MORELLI ANDRADE DOS SANTOS,True
19,19,861,LSA - LUCIANO,2.933139e+13,LLA COMERCIO E SERVICOS DE TAPECARIA LTDA,LSA - LUCIANO,True
21,21,921,SACCARO - DIRETO,NaN,SACCARO - DIRETO,SACCARO - DIRETO,True
24,24,1241,GABRIELA SIQUEIRA VIEIRA,NaN,GABRIELA SIQUEIRA VIEIRA,GABRIELA SIQUEIRA VIEIRA,True
26,26,1565,LSA - LITORAL,NaN,LSA - LITORAL,LSA - LITORAL,True
38,38,670,A.J.P. REPRESENTACOES LTDA,9.131207e+12,A.J.P. REPRESENTACOES LTDA,A.J.P. REPRESENTACOES LTDA,True
39,39,672,JARDIM - VITOR,1.702277e+13,VITOR C. JARDIM REPRESENTACOES,JARDIM - VITOR,True
41,41,741,BRETON - DIRETO,NaN,BRETON - DIRETO,BRETON - DIRETO,True
42,42,841,EXCLUSIVA CENTURY - MARINGÁ,8.761211e+12,LUIZ DAMASCENO MOVEIS E DECORACOES LTDA,EXCLUSIVA CENTURY - MARINGÁ,True
44,44,1121,LSA - MARCIA MORELLI,NaN,LSA - MARCIA MORELLI,LSA - MARCIA MORELLI,True
46,46,1261,NATAN SERVICOS DE REPRESENTACOES LTDA,4.188498e+13,NATAN SERVICOS DE REPRESENTACOES LTDA,NATAN SERVICOS DE REPRESENTACOES LTDA,True
52,52,1541,LSA- LITORAL,NaN,LSA- LITORAL,LSA- LITORAL,True
55,55,641,LSA - LUCIANO FILHO,NaN,LSA - LUCIANO MORETTI DE ABREU,LSA - LUCIANO FILHO,True
56,56,643,EN7 - EDUARDO,1.452660e+13,EN7 REPRESENTACOES. CONSULTORIA TREINAMENTO E ...,EN7 - EDUARDO,True
58,58,649,J C - JÚLIO CESAR,8.176085e+13,J C GESTAO E ADMINISTRACAO DE PROPRIEDADE S/S ...,J C - JÚLIO CESAR,True
59,59,650,WSA - WASHINGTON,5.118949e+12,WASHINGTON AZEVEDO REPRESENTACOES LTDA,WSA - WASHINGTON,True
69,69,648,GRX REPRESENTAÇÕES,1.716565e+13,GRX REPRESENTACOES COMERCIAIS LTDA,GRX REPRESENTAÇÕES,True

In [43]:
#trep_focco.loc[trep_focco['nome_representante']=='L.S.A - PAULO SERGIO PORTO']