In [21]:
from sqlalchemy import create_engine
import pandas as pd
import xmlrpc.client


engine = create_engine(
    "postgresql+psycopg2://consulta:consulta@10.1.57.244:5432/dwfocco"
)
host = "10.1.57.244"
database = "dwfocco"
username = "consulta"
password = "consulta"

In [22]:
query = r"""
        WITH base AS (
            SELECT
                tp_it.ID AS PRECO_FOCCO_ID,
                it.COD_ITEM,
                tp.COD_PREVEN,
                tp.DESCRICAO AS TABELA_DESCRICAO,
                REGEXP_REPLACE(it.DESC_TECNICA, '^MODELO\s+', '', 'i') AS PRODUTO,
        
                car.COD_CAR,
                var.MNEMONICO,
                it_car.SEQ,
        
                tp_it.DES_FORMULA AS FORMULA,
                tp_it.PRECO AS PRECO,
                gci.DESCRICAO as DESCRICAO
        
            FROM TPRECOSVEN_IT tp_it
        
            JOIN TPRECOSVEN tp
                ON tp.ID = tp_it.TPRVEN_ID
        
            JOIN TITENS_COMERCIAL itcm
                ON itcm.ID = tp_it.ITCM_ID
        
            JOIN TITENS_EMPR it_emp
                ON it_emp.ID = itcm.ITEMPR_ID
        
            JOIN TITENS it
                ON it.ID = it_emp.ITEM_ID
        
            LEFT JOIN TPRC_REGRAS_COM reg_com
                ON reg_com.TPRVEN_IT_ID = tp_it.ID
        
            LEFT JOIN TCARACTERISTICAS car
                ON car.ID = reg_com.TCARAC_ID
        
            LEFT JOIN TITENS_CAR it_car
                ON it_car.ITEMPR_ID = it_emp.ID
               AND it_car.TCARAC_ID = reg_com.TCARAC_ID
        
            LEFT JOIN TPRC_REGRAS_VAR_COM reg_var
                ON reg_var.REGRA_COM_ID = reg_com.ID
        
            LEFT JOIN TVARIAVEIS var
                ON var.ID = reg_var.TVAR_ID
        
            LEFT JOIN TGRP_CLAS_ITE gci
                ON gci.ID = itcm.grp_clas_id
        
            WHERE tp_it.SIT = 1
              --AND it.COD_ITEM = '20001'
              AND tp.COD_PREVEN = 155
        )
        
        SELECT
            PRECO_FOCCO_ID,
            COD_ITEM,
            COD_PREVEN,
            TABELA_DESCRICAO,
            PRODUTO,
            DESCRICAO,
        
            MAX(MNEMONICO) FILTER (WHERE COD_CAR = 'MODULACAO')      AS MODULACAO,
            MAX(MNEMONICO) FILTER (WHERE COD_CAR = 'COMP_MODULO')    AS COMP_MODULO,
            MAX(MNEMONICO) FILTER (WHERE COD_CAR = 'PROF_PRODUTO')   AS PROF_PRODUTO,
        
            REPLACE(
                MAX(MNEMONICO) FILTER (WHERE COD_CAR = 'FX_TEC'),
                'FX ',
                ''
            ) AS FAIXA,
        
            MAX(MNEMONICO) FILTER (WHERE COD_CAR = 'TIPO_ACAB')      AS TIPO_ACAB,
            MAX(MNEMONICO) FILTER (WHERE COD_CAR = 'EMBAL_REFORCADA') AS EMBALAGEM,
        
            STRING_AGG(
                MNEMONICO,
                CHR(35)
                ORDER BY SEQ
            ) FILTER (WHERE MNEMONICO IS NOT NULL) AS CONFIGURACAO,
        
            FORMULA,
        
            STRING_AGG(
                COD_CAR || ':' || MNEMONICO,
                CHR(124)
                ORDER BY SEQ
            ) FILTER (
                WHERE COD_CAR IS NOT NULL
                  AND MNEMONICO IS NOT NULL
            ) AS RESP,
        
            PRECO
        
        FROM base
        
        GROUP BY
            PRECO_FOCCO_ID,
            COD_ITEM,
            COD_PREVEN,
            TABELA_DESCRICAO,
            PRODUTO,
            DESCRICAO,
            FORMULA,
            PRECO
        
        ORDER BY
            COD_ITEM,
            PRODUTO,
            MODULACAO,
            COMP_MODULO,
            PROF_PRODUTO,
            FAIXA,
            TIPO_ACAB,
            EMBALAGEM;
        """

In [24]:
df = pd.read_sql(query, engine)

engine.dispose()

In [25]:
df

,preco_focco_id,cod_item,cod_preven,tabela_descricao,produto,descricao,modulacao,comp_modulo,prof_produto,faixa,tipo_acab,embalagem,configuracao,formula,resp,preco
0,12313160,10000,155,TABELA CENTURY 2026.2,ACABAMENTO,ACABAMENTO,NaN,NaN,NaN,B,NaN,NaN,FX B,NaN,FX_TEC:FX B,186.300
1,12313154,10000,155,TABELA CENTURY 2026.2,ACABAMENTO,ACABAMENTO,NaN,NaN,NaN,C,NaN,NaN,FX C,NaN,FX_TEC:FX C,221.490
2,12313155,10000,155,TABELA CENTURY 2026.2,ACABAMENTO,ACABAMENTO,NaN,NaN,NaN,D,NaN,NaN,FX D,NaN,FX_TEC:FX D,261.855
3,12313156,10000,155,TABELA CENTURY 2026.2,ACABAMENTO,ACABAMENTO,NaN,NaN,NaN,E,NaN,NaN,FX E,NaN,FX_TEC:FX E,308.430
4,12313161,10000,155,TABELA CENTURY 2026.2,ACABAMENTO,ACABAMENTO,NaN,NaN,NaN,F,NaN,NaN,FX F,NaN,FX_TEC:FX F,377.775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252054,12312852,6523,155,TABELA CENTURY 2026.2,KIT MOTORIZADO,KIT,NaN,NaN,NaN,NaN,NaN,NaN,TOUCH SMART#1 AS#ABERTURA DE 40CM,NaN,TIPO_KIT_MOT:TOUCH SMART|QTD_AS:1 AS|TAMANHO_A...,2240.000
252055,12312801,6523,155,TABELA CENTURY 2026.2,KIT MOTORIZADO,KIT,NaN,NaN,NaN,NaN,NaN,NaN,SOFT TOUCH SMART ITALIANO#4 AS,NaN,TIPO_KIT_MOT:SOFT TOUCH SMART ITALIANO|QTD_AS:...,6094.000
252056,12312851,6523,155,TABELA CENTURY 2026.2,KIT MOTORIZADO,KIT,NaN,NaN,NaN,NaN,NaN,NaN,TOUCH SMART#1 AS#ABERTURA DE 35CM,NaN,TIPO_KIT_MOT:TOUCH SMART|QTD_AS:1 AS|TAMANHO_A...,2092.000
252057,12312850,6523,155,TABELA CENTURY 2026.2,KIT MOTORIZADO,KIT,NaN,NaN,NaN,NaN,NaN,NaN,TOUCH SMART#1 AS#ABERTURA DE 156CM,NaN,TIPO_KIT_MOT:TOUCH SMART|QTD_AS:1 AS|TAMANHO_A...,3809.000
252058,12312849,6523,155,TABELA CENTURY 2026.2,KIT MOTORIZADO,KIT,NaN,NaN,NaN,NaN,NaN,NaN,TOUCH SMART ITALIANO#4 AS,NaN,TIPO_KIT_MOT:TOUCH SMART ITALIANO|QTD_AS:4 AS,5363.000

In [29]:
df_caixa = df[
    #df["produto"].str.contains("MANIFOLD", case=False, na=False) | 
    df["produto"].str.contains("CARTIER", case=False, na=False)
]

df_caixa

,preco_focco_id,cod_item,cod_preven,tabela_descricao,produto,descricao,modulacao,comp_modulo,prof_produto,faixa,tipo_acab,embalagem,configuracao,formula,resp,preco
173778,12171888,21008,155,TABELA CENTURY 2026.2,CARTIER,SOFAS ARTICULADOS,2B 1AS,1.58M,NaN,B,NaN,CAIXA MADEIRA,2B 1AS#1.58M#FX B#FX E#TOUCH#CAIXA MADEIRA,NaN,MODULACAO:2B 1AS|COMP_MODULO:1.58M|FX_TEC:FX B...,9372.0
173779,12171926,21008,155,TABELA CENTURY 2026.2,CARTIER,SOFAS ARTICULADOS,2B 1AS,1.58M,NaN,B,NaN,CAIXA MADEIRA,2B 1AS#1.58M#FX B#FX H#SOFT TOUCH#CAIXA MADEIRA,NaN,MODULACAO:2B 1AS|COMP_MODULO:1.58M|FX_TEC:FX B...,10163.0
173780,12171886,21008,155,TABELA CENTURY 2026.2,CARTIER,SOFAS ARTICULADOS,2B 1AS,1.58M,NaN,B,NaN,CAIXA MADEIRA,2B 1AS#1.58M#FX B#FX E#TOUCH SMART#CAIXA MADEIRA,NaN,MODULACAO:2B 1AS|COMP_MODULO:1.58M|FX_TEC:FX B...,10629.0
173781,12171929,21008,155,TABELA CENTURY 2026.2,CARTIER,SOFAS ARTICULADOS,2B 1AS,1.58M,NaN,B,NaN,CAIXA MADEIRA,2B 1AS#1.58M#FX B#FX H#TOUCH SMART#CAIXA MADEIRA,NaN,MODULACAO:2B 1AS|COMP_MODULO:1.58M|FX_TEC:FX B...,11136.0
173782,12171883,21008,155,TABELA CENTURY 2026.2,CARTIER,SOFAS ARTICULADOS,2B 1AS,1.58M,NaN,B,NaN,CAIXA MADEIRA,2B 1AS#1.58M#FX B#FX E#SOFT TOUCH#CAIXA MADEIRA,NaN,MODULACAO:2B 1AS|COMP_MODULO:1.58M|FX_TEC:FX B...,9656.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177773,12179805,21008,155,TABELA CENTURY 2026.2,CARTIER,SOFAS ARTICULADOS,2B 1AS,2.38M,NaN,J,NaN,SEM CX MADEIRA,2B 1AS#2.38M#FX J#FX G#SOFT TOUCH SMART#SEM CX...,NaN,MODULACAO:2B 1AS|COMP_MODULO:2.38M|FX_TEC:FX J...,16586.0
177774,12179810,21008,155,TABELA CENTURY 2026.2,CARTIER,SOFAS ARTICULADOS,2B 1AS,2.38M,NaN,J,NaN,SEM CX MADEIRA,2B 1AS#2.38M#FX J#FX G#SOFT TOUCH#SEM CX MADEIRA,NaN,MODULACAO:2B 1AS|COMP_MODULO:2.38M|FX_TEC:FX J...,15777.0
177775,12179815,21008,155,TABELA CENTURY 2026.2,CARTIER,SOFAS ARTICULADOS,2B 1AS,2.38M,NaN,J,NaN,SEM CX MADEIRA,2B 1AS#2.38M#FX J#FX G#TOUCH SMART#SEM CX MADEIRA,NaN,MODULACAO:2B 1AS|COMP_MODULO:2.38M|FX_TEC:FX J...,16751.0
177776,12179820,21008,155,TABELA CENTURY 2026.2,CARTIER,SOFAS ARTICULADOS,2B 1AS,2.38M,NaN,J,NaN,SEM CX MADEIRA,2B 1AS#2.38M#FX J#FX G#TOUCH#SEM CX MADEIRA,NaN,MODULACAO:2B 1AS|COMP_MODULO:2.38M|FX_TEC:FX J...,15493.0
177777,12179825,21008,155,TABELA CENTURY 2026.2,CARTIER,SOFAS ARTICULADOS,2B 1AS,2.38M,NaN,J,NaN,SEM CX MADEIRA,2B 1AS#2.38M#FX J#FX H#SOFT TOUCH SMART#SEM CX...,NaN,MODULACAO:2B 1AS|COMP_MODULO:2.38M|FX_TEC:FX J...,16824.0

In [32]:
df[["cod_item", "produto", "faixa", "configuracao", "resp", "preco"]].to_excel("CARTIER.xlsx", index=False)

In [33]:
df["descricao"].unique()

<StringArray>
[        'ACABAMENTO',              'BRACO',       'SOFAS LIVING',
 'SOFAS LIVING CURVO',               'CAPA',  'SOFAS ARTICULADOS',
          'POLTRONAS',              'PUFFS',              'BANCO',
           'BANQUETA',            'CADEIRA',               'MESA',
     'MESA DE CENTRO',     'MESA DE JANTAR',            'MESA AP',
              'CAMAS',             'BIOMBO',            'ESTANTE',
           'APARADOR',             'BUFFET',            'ESPELHO',
             'TECIDO',          'ALMOFADAS',             'OUTROS',
                'KIT']
Length: 25, dtype: str